language: ruby
rvm:
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
script: bundle exec rspec spec
env:
  - DB=sqlite
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/