development:
  paypal:
    sandbox:     true
    username:    "seller_1354580504_biz_api1.pablocantero.com"
    password:    "1354580523"
    signature:   "AiPC9BjkCyDFQXbSkoZcgqH3hpacAHqtmvCOKJGgALmZG7.b5SzXsIQF"
    return_url:  "http://localhost:3000/pro/paypal/thank_you"
    cancel_url:  "http://localhost:3000/pro/paypal/canceled"
    ipn_url:     "http://localhost:3000/pro/paypal/ipn"
    description: "Puts Mail Pro Account Subscription"
    amount:      "2.99"
    currency:    "USD"
test:
  paypal:
    sandbox:     true
    username:    "seller_1354580504_biz_api1.pablocantero.com"
    password:    "1354580523"
    signature:   "AiPC9BjkCyDFQXbSkoZcgqH3hpacAHqtmvCOKJGgALmZG7.b5SzXsIQF"
    return_url:  "http://localhost:3000/pro/paypal/thank_you"
    cancel_url:  "http://localhost:3000/pro/paypal/canceled"
    ipn_url:     "http://localhost:3000/pro/paypal/ipn"
    description: "Puts Mail Pro Account Subscription"
    amount:      "2.99"
    currency:    "USD"
production:
  paypal:
    sandbox:     true
    username:    "seller_1354580504_biz_api1.pablocantero.com"
    password:    "1354580523"
    signature:   "AiPC9BjkCyDFQXbSkoZcgqH3hpacAHqtmvCOKJGgALmZG7.b5SzXsIQF"
    return_url:  "http://putsmail.com/pro/paypal/thank_you"
    cancel_url:  "http://putsmail.com/pro/paypal/canceled"
    ipn_url:     "http://putsmail.com/pro/paypal/ipn"
    description: "Puts Mail Pro Account Subscription"
    amount:      "2.99"
    currency:    "USD"

